config/routes.rb
  resources :system_settings do 
    collection do
      get :new_setting
      delete :delete_system_setting
      get :delete_system_setting
    end
  end

  resources :kpi do 
    collection do
      get :kpi_data_on_date
    end
  end

  resources :manage_nhs_account do 
    collection do
      get :update_clinic_account_status
      post :get_filter_data
      
    end
  end
  resources :unregister_from_email do 
    collection do
      post :unregister_email_from_list
    end
  end
  
  resources :clinic do 
    collection do
      get  :new_organization
      get  :delete_organization
      put  :update_organization
      post :create_organization
      get  :list_organization_user
      get  :edit_user
      get  :get_organization_detail
      get  :new_organization_user
      get  :delete_organization_user
      put  :update_organization_user
      post :create_organization_user
      get :import_user_from_file
      post :save_imported_organization_user

    end
  end
  resources :nhs_request_manager do 
    collection do
      get :nhs_news_request
      get :search_data
      get :nhs_search_request
      get :nhs_search_request_output
      get :nhs_news_request_output
      get :get_data
      post :nhs_search_data
      get :nhs_search_data
      get :show_saved_articles
      get :show_saved_media
      get :get_organisation_data
      get :show_organisation_data
    end
  end

  
  resources :test_page

  resources :nhs_data do
    collection do 
      post :list_data
    end 
  end
  
  resources :role_for_admin_panel do 
    collection do
      get :new_role
      get :delete_role
    end
  end
  resources :module_access_for_role do 
    collection do
      get :new_module_access
      get :delete_module_access
    end
  end
  resources :batch_notification_manager do 
    collection do
      get :new_batch_notification
      get :delete_batch_notification
      get :test_notification_on
      get :clear_notification_count
    end
  end

  resources :alexa do 
    collection do
    end
  end

  resources :face_plus do 
    collection do
      get :get_response_from_face_plus_plus
       post :get_response_from_face_plus_plus
    end
  end

  resources :system_template do 
    collection do
      get :get_gpsoc_immunisation_jab_detail
      get :get_system_jab_detail
       get :autocomplete_system_immunisation_jab_title
       get :autocomplete_gpsoc_immunisation_jab_title
       get :autocomplete_nhs_syndicate_content_title
       get :new_template
       get :delete_template
       get :add_syndicated_content_action_card_category
       post :save_syndicated_content_action_card_category
       get :get_system_data_for_selected_country
       get :new_system_record
       get :show_system_record
       get :clone_form_for_country
       post :clone_complete_data_for_country
       post :create_system_record
       put :update_system_record
       get :delete_system_record
       get :edit_system_record
       get :next_system_record
       get :previous_system_record
       get :clone_system_record
       get :duplicate_system_record
       post :add_existing_checkup_test
       get :get_linked_syndicated_content
    end
  end

  

  resources :tool_list_maintenance do 
    collection do
      get :new_tool
      get :delete_tool
    end
  end

  resources :faq do 
    collection do
      get :new_topic
      get :new_subtopic
      get :new_question
      get :new_answer
      
      post :create_topic
      post :create_subtopic
      post :create_question
      post :create_answer

      put :update_topic
      put :update_subtopic
      put :update_question
      put :update_answer

      get :edit_topic
      get :edit_subtopic
      get :edit_question
      get :edit_answer

      get :show_topic
      get :show_subtopic
      get :show_question
      get :show_answer
      get :autocomplete_system_question_custom_id
      get :delete_record
      get :test_question_scenario_validation_to_assign
    end
  end

  resources :subscription_maintenance do 
    collection do
      get :new_subscription
      get :delete_subscription
      get :subscription_report
      get :subscription_history_paginated_data
      get :get_users_list_checking_subcription_list
      get :paginated_data
    end
  end

  resources :action_card_list_maintenance do 
    collection do
      get :new_action_card
      get :delete_action_card
    end
  end

  resources :api_log do 
    collection do
      get :get_filter_data
      post :get_filter_data
      get :new_action_card
      get :delete_action_card
      get :admin_panel_access_log
      get :paginated_data
      get :event_log_data
      get :event_list
      get :get_event_description
      get :tpp_logs
      get :tpp_log_paginated_data
      post :get_emis_filter_data
      get :emis_logs
      get :emis_log_paginated_data
      post :get_nhs_api_filter_data
      get :nhs_api_log_paginated_data
      get :nhs_api_logs
      get :cvtm_purchase_event_log_data
      get :emis_logs
      get :emis_log_paginated_data
      get :edit_event
      put :update_event
    end
  end

  resources :user_role_for_admin_panel do 
    collection do
      get :new_role
      get :delete_role
    end
  end

  resources :scenario_details do 
    collection do
      get  :new_scenario
      post :add_scenario 
      get  :delete_scenario
      get  :edit_scenario
      put  :update_scenario
      get  :get_linked_items
      get  :paginated_data
      get  :clone_scenario
      get  :go_to_next_scenario
      get  :go_to_previous_scenario
      get  :edit_next_scenario
      get  :edit_previous_scenario 
      get  :test_notification_validation_to_assign
    end
  end

  resources :nhs_syndicated_content do 
    collection do
      get  :new_syndicated_content
      post :add_syndicated_content
      get  :delete_syndicated_content
      get  :edit_syndicated_content
      put  :update_syndicated_content
      get  :get_linked_items
      get  :paginated_data
      get  :clone_syncdicated_content
      get  :go_to_next_syndicated_content
      get  :go_to_previous_syndicated_content
      get  :edit_next_syndicated_content
      get  :edit_previous_syndicated_content
      get  :show_content
      get :fetch_content
      get :link_with_tool
      get :get_country_list_for_tool_class
      get :autocomplete_link_tool_title
      post :save_link_tool_linking
      get :get_linkd_tool_with_sydicated_content
      get :delink_tool_with_syndicated_content
       
    end
  end

  resources :pointers do
    collection do 
      get :autocomplete_system_scenario_scenario_details_title
      get :autocomplete_system_pointer_custom_id
      post :search_pointer
      get :search_pointer
      get :edit_pointer_link
      put :update_pointer_link
      get :edit_pointer
      get :test_notification_validation_to_asign
      put :update_pointer
      get :validate_all_pointer_links
      put :update_pointer_status
      get :delete_pointer
      get :clone_pointer
      get :get_pointer_history
      get :delete_pointer_link
      get :clone_pointer_link
      get :new_pointer
      get :new_pointer_link
      get :validate_pointer_link
      post :create_pointer
      get :paginated_link_data
      post :create_pointer_link
      get :test_notification_on
      get :test_notification_off
      get :go_to_next_pointer
      get :go_to_previous_pointer
      get :edit_next_pointer_link
      get :edit_previous_pointer_link
      get :edit_next_pointer
      get :edit_previous_pointer 
      get :push_pointer_count_report
      get :get_pointer_history
      get :get_link_details
      get :all_pointer_links
    end 
  end
  resources :users do
     collection do
       get :approve
       put :aprove_user  
       get :update_user_status 
       get :delete_user 
       get :report
       get :user_not_signed_in_since_form
       get :user_not_signed_in_since
       get :user_type
       post :search    
       get :search
       post :search_user    
       get :search_user    
       get :update_user_for_mail_registration 
       get :get_user_device_details
       get :edit_user_detail   
       get :get_user_detail   
       post :update_user_datail   
       get :push_notification_report
       get :push_notification_report_identifier_wise
       get :push_notification_response_report
       get :push_notification_identifier_response_summary_report
       post :push_notification_identifier_response_summary_report
       get :user_subscription_change_form
       get :edit_credit_in_family_cvtme_purchase
       get :update_credit_in_family_cvtme_purchase
       get :update_user_subscription
       get :user_login_atleast_once_at_interval_in_duration_form 
       get :user_login_atleast_once_at_interval_in_duration
       get :get_push_notification_identifier_detail
       get :user_subscription_history
       get :user_families_detail
       get :home
       get :deleted_user_details
       get :kpi_data
     end
  end
  resources :questionnaires do

    resources :questions do
      get :take_quiz
      post :take_quiz
      post :save_answer
    end
    resources :relevances
  end
end
resources :health do
  collection do 
    get :get_detail
    get :edit
    get :new_health_record
    get :get_health_detail
    post :create_record
    post :update_record
    get :delete_parameter
    get :health_info
    get :close_info_pop
  end
end

resources :immunisation do 
  collection do
    # get :new_vaccination
    get :new_jab
    post :save_jab
    get :edit_jab
    put :update_jab
    get :delete_jab
    get :immunisation_info
    get :close_info_pop
    get :upcoming_jabs
    get :jab_detail
  end
end

resources :score  

resources :vaccination do
  collection do
    get :add_vaccin
    get :delete_vaccin
    get :edit_vaccin
    put :update_vaccination
  end
end

resources :timeline do
  collection do
    get :pics
    get :media
    get :automated_timeline

app/controllers/api/v4/user/faq_controller.rb
class Api::V4::User::FaqController < ApiBaseController
  
  # Get
  # /api/v4/user/faq/get_topic_list.json?token=AuSnoCzp2uceDGA1JGqb
  # params = {:token=>}  
  def get_topic_list
    topics = System::Faq::Topic.sort_by_sort_order.entries
    render json: {status: StatusCode::Status200, topic_list:topics} 
  end


  # Get
  # /api/v4/user/faq/get_subtopic_list.json?token=AuSnoCzp2uceDGA1JGqb
  # params = {:token=>,:topic_id=>}  
  def get_subtopic_list
    topic = System::Faq::Topic.find(params[:topic_id])
    sub_topics = topic.sub_topics.sort_by_sort_order.entries
    render json: {status: StatusCode::Status200, :topic=>topic, subtopic_list:sub_topics} 
  end
  
  # Get
  # /api/v4/user/faq/get_question_detail.json?token=AuSnoCzp2uceDGA1JGqb&topic_id=5b6d2ce2f9a2f3610700000f
  # params = {:question_id=>,:token=>}
  def get_question_detail
    if params[:question_id].blank? 
      subtopic = System::Faq::SubTopic.find(params[:subtopic_id])
      questions = subtopic.questions.sort_by_sort_order.entries
      question_detail = questions.map{|question| question.get_json(current_user)} 
    else
      question = System::Faq::Question.find(params[:question_id])
      subtopic = System::Faq::SubTopic.find(question.sub_topic_id)
      question_detail = question.get_json(current_user)
    end
    topic = System::Faq::Topic.find(subtopic.topic_id)
    render json: {status: StatusCode::Status200, topic:topic, sub_topic:subtopic,question_detail:question_detail} 
  end

  # Get
  # api/v4/user/faq.json?token=3PQP4v3XxT53zXxt5JBJ
  # params = {:subtopic_id=>}
  def index
    begin
      json_resposne = System::Faq::Topic.topic_list_response(current_user,params)
      status = StatusCode::Status200
      message = ''
    rescue Exception=>e
      message = e.message
      @error = e.message
      status = StatusCode::Status100
    end
    json = { status: status, message: message, error: @error }
    json.merge!(json_resposne) if json_resposne
    render json: json
  end

  # /api/v4/user/faq/user_feedback.json?token=3PQP4v3XxT53zXxt5JBJ&question_id=5b75827d7a1d5037b0000003&helpful_to_user=yes
  def user_feedback
    begin
      System::Faq::AnswerFeedback.create_feedback(params, current_user)
      status = StatusCode::Status200
      message = Message::API[:success][:update_faq_feedback]
    rescue Exception=>e
      message = e.message
      @error = e.message
      status = StatusCode::Status100
    end
    json = { status: status, message: message, error: @error }
    render json: json
  end

end

app/controllers/api/v5/user/faq_controller.rb
class Api::V5::User::FaqController < ApiBaseController
  before_filter :set_api_version
  
  # Get
  # /api/v4/user/faq/get_topic_list.json?token=AuSnoCzp2uceDGA1JGqb
  # params = {:token=>}  
  def get_topic_list
    topics = System::Faq::Topic.sort_by_sort_order.entries
    render json: {status: StatusCode::Status200, topic_list:topics} 
  end


  # Get
  # /api/v4/user/faq/get_subtopic_list.json?token=AuSnoCzp2uceDGA1JGqb
  # params = {:token=>,:topic_id=>}  
  def get_subtopic_list
    topic = System::Faq::Topic.find(params[:topic_id])
    sub_topics = topic.sub_topics.sort_by_sort_order
    render json: {status: StatusCode::Status200, :topic=>topic, subtopic_list:sub_topics} 
  end
  
  # Get
  # /api/v4/user/faq/get_question_detail.json?token=AuSnoCzp2uceDGA1JGqb&topic_id=5b6d2ce2f9a2f3610700000f
  # params = {:question_id=>,:token=>}
  def get_question_detail
    if params[:question_id].blank? 
      subtopic = System::Faq::SubTopic.find(params[:subtopic_id])
      questions = subtopic.questions.sort_by_sort_order
      question_detail = questions.map{|question| question.get_json(current_user)} 
    else
      question = System::Faq::Question.find(params[:question_id])
      subtopic = System::Faq::SubTopic.find(question.sub_topic_id)
      question_detail = question.get_json(current_user)
    end
    topic = System::Faq::Topic.find(subtopic.topic_id)
    render json: {status: StatusCode::Status200, topic:topic, sub_topic:subtopic,question_detail:question_detail} 
  end

  # Get
  # api/v4/user/faq.json?token=3PQP4v3XxT53zXxt5JBJ
  # params = {:subtopic_id=>}
  def index
    begin
      json_resposne = System::Faq::Topic.topic_list_response(current_user,params)
      status = StatusCode::Status200
      message = ''
    rescue Exception=>e
      message = e.message
      @error = e.message
      status = StatusCode::Status100
    end
    json = { status: status, message: message, error: @error }
    json.merge!(json_resposne) if json_resposne
    render json: json
  end

  # /api/v4/user/faq/user_feedback.json?token=3PQP4v3XxT53zXxt5JBJ&question_id=5b75827d7a1d5037b0000003&helpful_to_user=yes
  def user_feedback
    begin
      System::Faq::AnswerFeedback.create_feedback(params, current_user)
      status = StatusCode::Status200
      message = Message::API[:success][:update_faq_feedback]
    rescue Exception=>e
      message = e.message
      @error = e.message
      status = StatusCode::Status100
    end
    json = { status: status, message: message, error: @error }
    render json: json
  end
  
  def set_api_version
    @api_version = 5
  end

end

app/controllers/api/v6/user/faq_controller.rb
class Api::V6::User::FaqController < ApiBaseController
  before_filter :set_api_version
  
  # Get
  # /api/v4/user/faq/get_topic_list.json?token=AuSnoCzp2uceDGA1JGqb
  # params = {:token=>}  
  def get_topic_list
    topics = System::Faq::Topic.sort_by_sort_order.entries
    render json: {status: StatusCode::Status200, topic_list:topics} 
  end


  # Get
  # /api/v4/user/faq/get_subtopic_list.json?token=AuSnoCzp2uceDGA1JGqb
  # params = {:token=>,:topic_id=>}  
  def get_subtopic_list
    topic = System::Faq::Topic.find(params[:topic_id])
    sub_topics = topic.sub_topics.sort_by_sort_order
    render json: {status: StatusCode::Status200, :topic=>topic, subtopic_list:sub_topics} 
  end
  
  # Get
  # /api/v4/user/faq/get_question_detail.json?token=AuSnoCzp2uceDGA1JGqb&topic_id=5b6d2ce2f9a2f3610700000f
  # params = {:question_id=>,:token=>}
  def get_question_detail
    if params[:question_id].blank? 
      subtopic = System::Faq::SubTopic.find(params[:subtopic_id])
      questions = subtopic.questions.sort_by_sort_order
      question_detail = questions.map{|question| question.get_json(current_user)} 
    else
      question = System::Faq::Question.find(params[:question_id])
      subtopic = System::Faq::SubTopic.find(question.sub_topic_id)
      question_detail = question.get_json(current_user)
    end
    topic = System::Faq::Topic.find(subtopic.topic_id)
    render json: {status: StatusCode::Status200, topic:topic, sub_topic:subtopic,question_detail:question_detail} 
  end

  # Get
  # api/v4/user/faq.json?token=3PQP4v3XxT53zXxt5JBJ
  # params = {:subtopic_id=>}
  def index
    begin
      json_resposne = System::Faq::Topic.topic_list_response(current_user,params)
      status = StatusCode::Status200
      message = ''
    rescue Exception=>e
      message = e.message
      @error = e.message
      status = StatusCode::Status100
    end
    json = { status: status, message: message, error: @error }
    json.merge!(json_resposne) if json_resposne
    render json: json
  end

  # /api/v4/user/faq/user_feedback.json?token=3PQP4v3XxT53zXxt5JBJ&question_id=5b75827d7a1d5037b0000003&helpful_to_user=yes
  def user_feedback
    begin
      System::Faq::AnswerFeedback.create_feedback(params, current_user)
      status = StatusCode::Status200
      message = Message::API[:success][:update_faq_feedback]
    rescue Exception=>e
      message = e.message
      @error = e.message
      status = StatusCode::Status100
    end
    json = { status: status, message: message, error: @error }
    render json: json
  end
  
  def set_api_version
    @api_version = 6
  end

end

app/views/admin/faq/_answer_form.html.erb
<style type="text/css">
  .textBx-type2{
    background-color: #ffffff;
  }
</style>
  

 <br/>
 <br/>
 <br/>
 <br/>
<%= @answer.errors.full_messages.first if @answer.errors.any? %>
<% @is_new_record = @answer.new_record? %>
<% @url = @answer.new_record? ? "/admin/faq/create_answer" : "/admin/faq/update_answer"%>
<%= form_for @answer,url: @url, :html => { :multipart => true } do |f| %>
<div>
  <h2 class="space-bottom-1"><%= @is_new_record ? "Add" : "Update" %> answer</h2>
  <div class="form-type2">
    <div class="form-row no-margin-bottom">

    <div class="form-row">
        <label class="form-label">Title<%= " (Use ';' with sentance to create multiple answer)" if  @is_new_record  %></label>
         <%= f.text_area :title, class: "js-name textBx-type2"  %>
    </div> 

    <%= f.hidden_field :question_id, :value=>@question.id %>
    <%= hidden_field_tag :system_faq_answer_id, @answer.id %>
     
    <div class="form-type3"><div class="form-action-row">
       <%= f.submit (@answer.new_record? ? "Create": "Update"), class: "btn btn-type2", disable_with: "Saving.."  %>
  
    </div></div>
  </div>
</div>
<% end %>
  
 <%= link_to "Cancel", "/admin/faq/show_question?question_id=#{@question.id}", :method => "get",class: "btn btn-type2"  %>
 <br/>
 <br/>
 <br/>
 

app/views/admin/faq/_answer_list.html.erb
  <script type="text/javascript">
   $(document).ready(function() {
    var t = $('#answer').DataTable( {
      "columnDefs": [ {
            "searchable": false,
            "orderable": false,
            "targets": 0
        } ],
      "scrollX": true,
      "lengthMenu": [[-1,5, 10, 50, 100, 200], ["All", 5, 10, 50, 100, 200]],
      "order": [[ 0, "asc" ]]

    } );
    t.on( 'order.dt search.dt', function () {
        t.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
            cell.innerHTML = i+1;
        } );
    } ).draw();

    $('.js-delete').click( function () {
      this_obj = $(this);
      id = $(this).data("id");
      class_name = $(this).data("class_name");
      $.ajax({
        url: "delete_topic",
        data: {id:id,class_name:class_name},
        script: "script",
        success: function(){
          this_obj.parent().parent().remove()
        }
      });
       
    } );

} );
 </script> 
 <style type="text/css">
div.dataTables_scrollHead{
  padding: 0 0px;
  margin: 0px 19px 0px 1px;
}
 </style>
 
<br/>
<br/>
<h2> Answer List </h2>
<br/>
<%= link_to "Add New Answer", "/admin/faq/new_answer?question_id=#{@question.id}" %>  (Append new answer if any answer already exist )
<br/>
<br/>
<table id="answer" class="display" cellspacing="0" width="100%">
 
        <thead>
          <tr>
            <th>                                  </th>
            <th>Title                             </th>
            <!-- <th>Category                          </th> -->
            <th>Action                            </th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th></th>
            <th>Title                             </th>
            <!-- <th>Category                          </th> -->
            <th>Action                            </th>
          </tr>
        </tfoot>
        <tbody>
          <%if @answer.present? %>
            <% answer = @answer  %>
            <tr id="dataRow1">
              <td></td>
              <td > <%= answer.title %></td>
              <td> <%=link_to "","/admin/faq/edit_answer?system_faq_answer_id=#{answer.id}",class: "icon-pencil txt-link-type2 "  %>    <%= link_to "", "/admin/faq/delete_record?id=#{answer.id}&class_name=#{answer.class.to_s}&header_link=false",confirm: "Are you sure you want to delete?", remote: true, class: "icon-trash-o txt-link-type2 js-#{answer.id}" %>
              </td>
            </tr>
          <% end %>                  
      </tbody>
    </table> 
 <!-- </div>
    
  </div> -->
  <div class="CL"></div>
<!-- </div> -->
 

app/views/admin/faq/_question_form.html.erb
<style type="text/css">
  .textBx-type2{
    background-color: #ffffff;
  }
</style>
  

 <br/>
 <br/>
 <br/>
 <br/>
<%= @question.errors.full_messages.first if @question.errors.any? %>
<% @url = @question.new_record? ? "/admin/faq/create_question" : "/admin/faq/update_question"%>
<%= form_for @question,url: @url, :html => { :multipart => true } do |f| %>
<div>
  <h2 class="space-bottom-1">Add question</h2>
  <div class="form-type2">
    <div class="form-row no-margin-bottom">

    <div class="form-row">
        <label class="form-label">Title</label>
         <%= f.text_area :title, class: "js-name textBx-type2"  %>
    </div> 
    <div class="form-row">
        <label class="form-label">Sort Order</label>
         <%= f.select :sort_order, options_for_select((1..100),@question.sort_order)  %>
    </div> 

     <% scenario_detail = (@question.scenario_detail || {}) rescue {}%>
     <% value = scenario_detail.present? ? "ID: #{scenario_detail['custome_id']},  Title: #{scenario_detail['title']}" : nil %>
        <label class="form-label">Scenario(Type ID/Scenario description below to select)</label>
        <%= autocomplete_field_tag :system_scenario_custome_id,'',autocomplete_system_scenario_scenario_details_title_admin_pointers_path,:value=>value, :id_element=>'#system_scenario_detail_custom_id',:size=>120,'data-auto-focus' => true ,'min-length' => -1,:onfocus=>"javascript:$(this).autocomplete('search',' ');" %>
        
        <%=hidden_field_tag :system_scenario_detail_custom_id,scenario_detail['custome_id'] %>
    </div>
      <% notification_expiry = @question.notification_expiry.split(".") rescue [] %>
       <div class="form-row">
        <label class="form-label">Notification Expiry </label>
        <%= select_tag :notification_expiry_period, options_for_select(["NA"]+(0..365).to_a,notification_expiry[0].blank? ? "NA": notification_expiry[0]), :class => 'custom-select1  ' %>
        <%= select_tag :notification_expiry_frequency, options_for_select([["NA",""],['Day','day'],['Week','week'] ,['Month','month'],['Yearly','year']],notification_expiry[1]), :class => 'custom-select1  ' %> 
          
         
    </div>
    <%= f.hidden_field :sub_topic_id, :value=>@subtopic.id %>
    <%= hidden_field_tag :system_faq_question_id, @question.id %>
     <div class="form-row">
        <label class="form-label">Status</label>
        <%= f.select :status, options_for_select(["Active","Draft"],@question.status)   %>
          
    </div>
    <div class="form-type3"><div class="form-action-row">
       <%= f.submit (@question.new_record? ? "Create": "Update"), class: "btn btn-type2", disable_with: "Saving.."  %>
  
    </div></div>
  </div>
</div>
<% end %>
  
 <%= link_to "Cancel", "/admin/faq/show_question?question_id=#{@question.id}", :method => "get",class: "btn btn-type2"  %>
 <br/>
 <br/>
 <br/>
 <style type="text/css">
  .ui-autocomplete{ 
    overflow: auto;
    height: 179px;
  }
</style>

<script type="text/javascript">
$(document).ready(function(){
  $("body").on('keyup',"#system_scenario_custome_id", function(event) {
    if (event.keyCode == 8 || event.keyCode == 46)
    {
    if($("#system_scenario_custome_id").val().length < 1){
      $("#system_scenario_custome_id").focus();
    }
  }
  });
})
  
</script>

app/views/admin/faq/_subtopic_form.html.erb
<style type="text/css">
  .textBx-type2{
    background-color: #ffffff;
  }
</style>
  

 <br/>
 <br/>
 <br/>
 <br/>
 <%= @subtopic.errors.full_messages.first if @subtopic.errors.any? %>
<% @url = @subtopic.new_record? ? "/admin/faq/create_subtopic" : "/admin/faq/update_subtopic"%>
<%= form_for @subtopic,url: @url, :html => { :multipart => true } do |f| %>
<div>
  <h2 class="space-bottom-1">Add subtopic</h2>
  <div class="form-type2">
    <div class="form-row no-margin-bottom">

    <div class="form-row">
        <label class="form-label">Title</label>
         <%= f.text_field :title, class: "js-name textBx-type2"  %>
    </div> 
    <div class="form-row">
        <label class="form-label">Sort Order</label>
         <%= f.select :sort_order, options_for_select((1..100),@subtopic.sort_order)  %>
    </div> 

    <%= f.hidden_field :topic_id, :value=>@topic.id %>
    <%= hidden_field_tag :system_faq_subtopic_id, @subtopic.id %>
     <div class="form-row">
        <label class="form-label">Status</label>
        <%= f.select :status, options_for_select(["Active","Draft"],@subtopic.status)    %>
          
    </div>
    <div class="form-type3"><div class="form-action-row">
       <%= f.submit (@subtopic.new_record? ? "Create": "Update"), class: "btn btn-type2", disable_with: "Saving.."  %>
  
    </div></div>
  </div>
</div>
<% end %>
  
 <%= link_to "Cancel", "/admin/faq/show_subtopic?subtopic_id=#{@subtopic.id}", :method => "get",class: "btn btn-type2"  %>
 <br/>
 <br/>
 <br/>
 

app/views/admin/faq/delete_record.js.erb
table = $("#<%=@table_id%>").DataTable();
<% if @header_link_status.to_s == "true"%>
    <% if @parent_record.present? %>
      <% class_name = @parent_record.class.to_s.split("::").last.downcase %>
      window.location.href = "<%= "/admin/faq/show_#{class_name}?#{class_name}_id=#{@parent_record.id.to_s}" %>"
    <% else %>
      window.location.href = "/admin/faq"
    <% end %>
<% else %>
  // table.row($(".js-<%=@record.id%>").parents('tr')).remove().draw(false);
  location.reload();
<% end %>

app/views/admin/faq/index.html.erb
<%= render :partial=>"/admin/faq/topic_list"%>

app/views/admin/faq/new_form.html.erb
<% if @form_for == "topic" %>
  <%= render :partial=>"/admin/faq/topic_form"%>
<% elsif @form_for == "subtopic" %>
  <%= render :partial=>"/admin/faq/subtopic_form"%>
<% elsif @form_for == "question" %>
  <%= render :partial=>"/admin/faq/question_form"%>
<% elsif @form_for == "answer" %>
  <%= render :partial=>"/admin/faq/answer_form"%>
<% end %>

app/views/admin/faq/new_topic.html.erb
<%= render :partial=>"/admin/faq/topic_form"%>

app/views/admin/faq/show_list.html.erb
<% if @form_for == "topic" %>
  <%= render :partial=>"/admin/faq/topic_list", :locals=>{:header_link=>true}%>
  <%= render :partial=>"/admin/faq/subtopic_list" ,:locals=>{:header_link=>false}%>
<% elsif @form_for == "subtopic" %>
  <%= render :partial=>"/admin/faq/subtopic_list" ,:locals=>{:header_link=>true}%>
  <%= render :partial=>"/admin/faq/question_list", :locals=>{:header_link=>false}%>
<% elsif @form_for == "question" %>
  <%= render :partial=>"/admin/faq/question_list",:locals=>{:header_link=>true}%>
  <%= render :partial=>"/admin/faq/answer_list", :locals=>{:header_link=>false}%>
<% end %>

app/views/admin/faq/test_question_scenario_validation_to_assign.js.erb
<% if @scenario.present? %>
alert("Name:<%=@scenario.scenario_title%>\r\nScore:<%=@scenario.effective_score%>\r\nDescription:<%=@scenario.topic%>")
<% else%>
alert("Scenario not assigned")
<% end %>