config/routes.rb
# require Rails.root.join('config/routes/api_v3_routes.rb')
# require Rails.root.join('config/routes/api_v4_routes.rb')
# require Rails.root.join('config/routes/api_v5_routes.rb')
# require Rails.root.join('config/routes/api_v6_routes.rb')

Nurturey::Application.routes.draw do
  extend ApiV6Routes
  extend ApiV5Routes
  extend ApiV4Routes
  extend ApiV3Routes
  namespace :api do
    
    namespace :v1 do
      get 'unread_objects_count' => 'notifications#unread_count'
      resources :notifications do
        collection do
          put :mark_read
        end  
      end    
      resources :users do 
        collection do 
          get :sign_in
          post :sign_in
          get :basic_set_up_evaluator_for_user
          get :child_members
          post :sign_in_via_facebook
          get :user_dashboard
          get :recent_items
          get :user_events
          post :upload_image
          post :upload_cover_image
          get :get_cover_image
          get :user_info
          put :dismiss_nutrient
          get :delete_account
          get :get_handhold_actions
          put :skipped_details
          post :skipped_details
          get :get_summary_screen
          get :nhs_authentication_completed
        end
      end
      resources :system_milestones do
        member do
          get :hh_milestones
        end  
      end  
      resources :milestones do
        member do
          get :milestones_for_graph
          post :upload_image
        end
        collection do
          put :add_multiple
          get :get_milestone_detail
        end  
      end  
      resources :nutrients do
        member do
          get :acitvate
          delete :deactivate
          get :nutrients_status
          put :update_nutrient_status
        end
        collection do
          get :categories
          get :change_category          
        end
      end  
      
      resources :documents do
        collection do
          post :save_documents
          get :search
          get :types          
        end  
        member do
          get :get_doc_detail    
          delete :delete_attachment
          post :upload_file
          # get :download
        end
      end  
      resources :timeline do
        collection do
          post :create_timeline
          put :update_timeline
          delete :delete_timeline
          get :get_timeline_detail
        end  
        member do
          post :upload_image
          get :get_hh_system_timelines
          post :add_hh_system_timelines
        end  
      end
      resources :invitations do
        collection do
          put 'update_status/:status', :to => "invitations#update_status"
          get 'update_status/:status', :to => "invitations#update_status"
          get 'invite_friend_to_nurturey'
        end  
      end    
    end

    namespace :v2 do
      get 'unread_objects_count' => 'notifications#unread_count'
      resources :notifications do
        collection do
          put :mark_read
        end  
      end
      
      resources :users , :except=>["create","show","index"] do 
        collection do 
          get :sign_in
          get :push_msg
          get :user_sign_out
          post :sign_in
          get :secure_sign_in
          post :secure_sign_in
          get :basic_set_up_evaluator_for_user
          get :child_members
          post :sign_in_via_facebook
          get :user_dashboard
          get :recent_items
          get :user_events
          post :upload_image_multipart          
          post :upload_image
          post :upload_cover_image
          get :get_cover_image
          get :user_info
          put :dismiss_nutrient
          get :delete_account
          get :get_handhold_actions
          put :skipped_details
          post :skipped_details
          get :get_summary_screen
          get :resend_confirmation_link
          get :test_action_notification
          get :set_default_cover_image
          get :set_version_controller
          post :enable_push_notification
        end
      end
      
      devise_for :users ,:controllers => {:passwords => "passwords", :sessions => "sessions",:registrations => 'api/v2/registrations',:confirmations=>'confirmations',:omniauth_callbacks => "omniauth_callbacks"} do
        resources :passwords do
          post :update
          collection do  
            put :secure_update
          end    
        end
        resources :registrations do 
          collection do 
            post :secure_signup
          end
        end
        resources :sessions do
          get :sign_in
        end
      end
      resources :system_milestones do
        member do
          get :hh_milestones
        end  
      end  
      resources :milestones do
        member do
          get :milestones_for_graph
          post :upload_image
        end
        collection do
          put :add_multiple
          get :get_milestone_detail
        end  
      end  
      resources :nutrients do
        member do
          get :acitvate
          delete :deactivate
          get :nutrients_status
          put :update_nutrient_status
        end
        collection do
          get :categories
          get :change_category          
        end
      end

      resources :families do
        resources :members, only: [] do
          resources :nutrients, only: :index
          resources :timeline, only: :index
          resources :milestones, only: :index
          resources :calendar, only: :index
          resources :health, only: :index
          resources :documents, only: :index
          resources :immunisation, only: :index
        end  
        collection do
          get :search_family
          get :select_role
          post :save_role
        end  
        member do
          post :join_this_family
          get :family_members  
          #get :join_this_family  # Temporary because form is not working with ajax      
        end   
        resources :member do
          collection do
            get :new_child
            post :create_child        
            get :new_elder
            post :create_elder 
          end
        end  
      end

      resources :documents do
        collection do
          post :save_documents
          get :search
          get :types          
        end  
        member do
          get :get_doc_detail    
          delete :delete_attachment
          post :upload_file
          # get :download
        end
      end  
      resources :timeline do
        collection do
          post :create_timeline_for_multi_member
          post :user_timeline
          post :index
          get :get_pre_defined_timeline
          post :create_timeline
          put :update_timeline
          delete :delete_timeline
          get :get_timeline_detail
        end  
        member do
          post :upload_image
          get :get_hh_system_timelines
          post :add_hh_system_timelines
        end  
      end
      resources :invitations do
        collection do
          put 'update_status/:status', :to => "invitations#update_status"
          get 'update_status/:status', :to => "invitations#update_status"
          get 'invite_friend_to_nurturey'
        end  
      end    
     
      resources :health do
        collection do 
          get :get_detail
          get :edit
          get :new_health_record
          get :get_health_detail
          post :create_record
          post :update_record
          get :delete_parameter
          get :health_info
          get :close_info_pop
        end
      end

      resources :immunisation do 
        collection do
          # get :new_vaccination
          get :new_jab
          post :save_jab
          get :edit_jab
          put :update_jab
          get :delete_jab
          get :immunisation_info
          get :close_info_pop
          get :upcoming_jabs
          get :jab_detail
        end
      end

      resources :score  

      resources :vaccination do
        collection do
          get :add_vaccin
          get :delete_vaccin
          get :edit_vaccin
          put :update_vaccination
        end
      end

      resources :timeline do
        collection do
          get :pics
          get :media
          get :automated_timeline
          post :save_auto_time
          get :skip_automated_timeline
          get :edit
          post :create_timeline
          put :update_timeline
          get :delete_timeline
          get :remind_later
          get :delete_timeline_pic
          get :timeline_info
        end
        member do
          get :facebook_preview
          post :send_to_facebook
        end  
      end

      resources :manage_family

      match "/calendar/dashboard" => "users#dashboard"
      match '/families/get_family_data'        => 'families#get_family_data', :as => :get_family_data 
      match '/families/join_family'        => 'families#join_family', :as => :join_family 
      match '/families/save_joined_family'        => 'families#save_joined_family', :as => :save_joined_family
      resources :calendar do
        collection do
          get :get_data
          get :get_parent_data
          post :create_event
          put :event_update
          get :edit_event
          get :event_delete
          get :get_event_datail
          # get  :timeline
          get :calendar_info
        end
      end


      post 'profile/delete_child_interest'
      
      resources :milestones do
        collection do
          put :add_multiple
          get :add_description
          get :change_category
          get :display_later
          get :milestones_info
        end  
        member do
          put :save_and_next
          get :skip
          delete :remove_picture
          get :display_picture
        end  
      end  

      resources :nutrients do
        collection do
          get :change_category
        end  
        member do

app/models/clinic/document.rb
class Clinic::Document
  include Mongoid::Document  
  include Mongoid::Timestamps
  #options = {current_user=>}
  def self.list_document(current_user,member,options={})
    member_id = member.id
    clinic_class = ::Clinic::ClinicDetail.get_clinic_linkable_class(current_user,member,"Documents",options)
    clinic_class.list_document(member_id,options)
  end

  #options = {current_user=>}
  def self.document_detail(current_user,member,document_id,options={})
    member_id = member.id
    clinic_class = ::Clinic::ClinicDetail.get_clinic_linkable_class(current_user,member,"Documents",options)
    clinic_class.get_document_content(member_id,document_id,options)
  end
end

app/models/clinic/smrthi/documents.rb
class Clinic::Smrthi::Documents
  
  # Emis::Prescribing.user_nominated_pharmacy(member_id,options)
  def self.list_document(member_id,options={})
    begin
      return {documents: [], status:200}
    rescue Exception=>e 
      return {message:e.message, status:100}
    end
  end

  def self.get_document_content(member_id,document_id,options={})
    begin
      return {document_data: nil, status:200}
    rescue Exception=>e 
      return {message:e.message, status:100}
    end
  end


end

app/controllers/api/v1/documents_controller.rb
 class Api::V1::DocumentsController < ApiBaseController

 	# GET http://localhost:3000/api/v1/documents.json?token=XrjzH88mP4syK1q4MTeb&member_id=546128200a9a99178300000d
 	def index
	  member = Member.where(id: params[:member_id]).first
	  @documents = member.documents if member
	  member["age"] = ApplicationController.helpers.calculate_age(member.birth_date) rescue ""
	  respond_to do |format|
	  	#format.json { render json: (documents || []) }
	  	format.json
	  end
	end
  
  # Get /api/v1/documents/get_doc_detail.json?token=XrjzH88mP4syK1q4MTeb&doc_id
	def get_doc_detail
	  @document = Document.where(id: params[:id]).first
	end

	# POST http://localhost:3000/api/v1/documents.json?token=XrjzH88mP4syK1q4MTeb
	# "member_id"=>"546128200a9a99178300000d", "document"=>{"name"=>"hiii", "document_type"=>"Health", "file"=>#<ActionDispatch::Http::UploadedFile:0x0000000b048868 @original_filename="Screenshot from 2015-02-18 21:14:05.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"document[file]\"; filename=\"Screenshot from 2015-02-18 21:14:05.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<File:/tmp/RackMultipart20150307-3267-reec7w>>}
	def create
	  member = Member.where(id: params[:member_id]).first
	  document = member.documents.new(params[:document]) if member
	  respond_to do |format|
	  	if document && document.save
	  	  message = Message::API[:success][:add_document]
	  	  format.json { render json: document.attributes.merge(file_path: document.file.path, message: message,status: StatusCode::Status200) }
	  	else
	  		message = Message::API[:error][:add_document]
	  	  format.json { render json: {:message=> message, :status=> StatusCode::Status100, :errors => document.try(:errors)} }
	  	end
	  end
	end

	# PUT http://localhost:3000/api/v1/documents/54fa95c20a9a995f0c000002.json?token=XrjzH88mP4syK1q4MTeb
	# Parameters: {"member_id"=>"546128200a9a99178300000d", "document"=>{"name"=>"doc3 updated", "document_type"=>"\"General\""}, "token"=>"XrjzH88mP4syK1q4MTeb", "id"=>"54fa95c20a9a995f0c000002"}
	# Parameters: {"utf8"=>"✓", "authenticity_token"=>"csBsF7lIRuCZfKCd2CgHOHlOAafYxRn5u+C+jH1tQfU=", "member_id"=>"546128200a9a99178300000d", "document"=>{"name"=>"doc3 updated", "document_type"=>"General", "file"=>#<ActionDispatch::Http::UploadedFile:0x00000007fee320 @original_filename="Screenshot from 2015-02-18 21:14:05.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"document[file]\"; filename=\"Screenshot from 2015-02-18 21:14:05.png\"\r\nContent-Type: image/png\r\n", @tempfile=#<File:/tmp/RackMultipart20150307-4305-1fu4z6v>>}
	def update
	  member = Member.where(id: params[:member_id]).first
	  document = member.documents.find(params[:id]) if member
	  # document.file = params[:upload_document].last if params[:upload_document]
	  respond_to do |format|
	    if document.update_attributes(params[:document])
     	  message = Message::API[:success][:update_document]
	      format.json { render json: document.attributes.merge(file_path: document.file.path, message: message,status: StatusCode::Status200 ) }
	    else
	      message = Message::API[:success][:update_document]
	      format.json { render json: {:errors => document.errors, :message=> message, :status=> StatusCode::Status100} }
	    end
	  end
	end	

	# DELETE http://localhost:3000/api/v1/documents/54fa95c20a9a995f0c000002.json?token=XrjzH88mP4syK1q4MTeb
	def destroy
	  @document = Document.where(id: params[:id]).first
	  @document.destroy
	  respond_to do |format|
	    format.json
	  end
	end	

	# GET http://localhost:3000/api/v1/documents/search?utf8=%E2%9C%93&member_id=546128200a9a99178300000d&Document%5Bname%5D=doc
	def search
	  member = Member.find(params[:member_id])
	  if params[:Document][:name].present?
	  	documents = member.documents.any_of(name: /#{params[:Document][:name]}.*/)
	  else
	  	documents = member.documents
	  end	
	  respond_to do |format|
	    format.json {render json: documents}	    
	  end
	end	

	# DELETE http://localhost:3000/api/v1/documents/548bfd0e0a9a997d21000008/delete_attachment
	def delete_attachment
	  @document = Document.find(params[:id])
	  @document.file = nil
	  @document.save
	  respond_to do |format|
	    format.json
	  end
	end

	# GET http://localhost:3000/api/v1/documents/types.json
	def types
	  respond_to do |format|
	  	format.json {render json: Document::DOC_TYPES.values}
	  end	
	end	

	# def download
	#   document = Document.find(params[:id])
	#   send_file document.file.path
	# end	

	def upload_file
	  @document = Document.find(params[:id])
	  decode_and_save_file(@document,params[:file_data]) if params[:file_data].present?
	rescue
	  render json: {status: StatusCode::Status100}
	end

	private

	def decode_and_save_file(nutrient,image_data)
	    member = nutrient.member
	    content = image_data
	    content.gsub!('\\r', "\r")
	    content.gsub!('\\n', "\n")
	    decode_base64_content = Base64.decode64(content)
	    File.open("public/documents/#{nutrient.class.name.downcase}_#{nutrient.id}.jpg", "wb") do |f|
	      f.write(decode_base64_content)
	    end
	    file = File.open("public/documents/#{nutrient.class.name.downcase}_#{nutrient.id}.jpg")
	    nutrient.file = file
	    nutrient.save if nutrient.valid?
	    File.delete("public/documents/#{nutrient.class.name.downcase}_#{nutrient.id}.jpg")
    end

 end	

app/controllers/api/v3/documents_controller.rb
 class Api::V3::DocumentsController < Api::V2::DocumentsController
   
  # GET http://localhost:3000/api/v1/documents.json?token=XrjzH88mP4syK1q4MTeb&member_id=546128200a9a99178300000d
 	def index
	  member = Member.where(id: params[:member_id]).first
	  @documents = member.documents if member
	  member["age"] = ApplicationController.helpers.calculate_age(member.birth_date) rescue ""
	  respond_to do |format|
	  	format.json
	  end
	end
   # GET http://localhost:3000/api/v3/documents/types.json
	def types
    render json: {status: StatusCode::Status200, document_types:Document::DOC_TYPES.values}	
	end

	# DELETE http://localhost:3000/api/v1/documents/54fa95c20a9a995f0c000002.json?token=XrjzH88mP4syK1q4MTeb
	def destroy
	  @document = Document.where(id: params[:id]).first
	  @document.destroy
	  respond_to do |format|
	    format.json
	  end
	end		
	# Get /api/v3/documents/get_doc_detail.json?token=XrjzH88mP4syK1q4MTeb&doc_id
	def get_doc_detail
	  @document = Document.where(id: params[:id]).first
	end

 end	

app/views/documents/_document_list.html.erb
<% if @documents.present? %>
  <% @documents.each do |document| %>
    <tr>
      <td class='break-word'>
        <!-- <i class="icon-pdf"></i>  -->
        <%= truncate(document.name, length: 20) %> 
      </td>
      <td> <%= document.document_type %></td>
      <td> <%= toDate(document.file_updated_at) %> </td>
      <td>
    	  <span class="actionBar">
            <%= link_to "","#html", data: {pop: edit_document_path(document), width: "600"}, class: "icon-pencil" %>
            &nbsp;
            <%= link_to "",download_document_path(document), class: "icon-download-file" if document.file.present? %>
            &nbsp;
            <%= link_to "",document_path(document.id), method: :delete, class: "icon-trash-o", remote: true, confirm: "Are you sure you want to delete?" %>
    	  </span>
      </td>
  </tr>
  <% end %>
<% else %>
  <% if params[:controller]=='documents' && params[:action]=='search' %>  
    <tr>
      <td colspan=4 style="text-align:center;">
        No search results found
      </td> 
    </tr>
  <% end %>  
<% end %>

app/views/documents/_documents_center_sec.html.erb
<!-- reapte user -->
<div class="singleBx-type8">
    <div class="titleBar-type3 clearFix">
        <h1 class="FL">
        <%=profile_image_tag(@member,"small") %>
            DOCUMENTS
        </h1>
        <div class="actionBar">
            
            <div class="serarch-box">
            <%= form_for :Document, url: search_documents_path, remote: true, method: :get do |f|  %>
                <i class="icon-search"></i>
                <%= hidden_field_tag :member_id, @member.id  %>
                <%= f.text_field :name, placeholder: "Search" %>
            <% end %>    
            </div>
            <%#= link_to "",list_google_doc_path(member_id: @member.id), class: "txt-link-type1 icon-gdrive", style: "margin-top:6px;" %>
            &nbsp;
            <%= link_to "Upload",'#html', data: {pop: new_document_path(member_id: @member.id), width: "600"}, class: "btn btn-big-type1 icon-plus", style: "margin-top:6px;" %>
        </div>
    </div>
    <div class="singleBx-type11 text-center table-type3">
        <table cellpadding="0" cellspacing="0" id="tableType1">
            <thead><tr>
                <th width="30%">Name</th>
                <th width="25%">Type</th>
                <th width="20%">Last Modified</th>
                <th width="25%">&nbsp;</th>
            </tr></thead>
            <tbody class="member_documents">
                <%= render partial: "document_list" %>            
            </tbody>
        </table>

    </div>
</div>

<script type="text/javascript">

    $(function () {
        //datatable
        $('#tableType1').dataTable({
            "scrollY": false,
            "scrollCollapse": true,
            "searching": false,
            "paging": false,
            "ordering": false,
            "oLanguage": {
                "sEmptyTable":"<div class='data-error empty-msg-1'><p>No documents uploaded yet. Keep your documents safe and accessible. We support pdf, doc, docx, xls, jpg and png. Click on the Upload button to get started.</p></div><br/>"
                // 'sEmptyTable':'<h2 class="txt-type-1 page-title-5 text-italic">No Documents Uploaded Yet!</h2> <i class="icon-pdf no-documents"></i> <p class="txt-type-3">Keep your documents safe and accessable. We support pdf, doc, docx, xls, jpg and png.</p>        <p class="page-title-5 no-margin-bottom">Click on the Upload button to get started!</p>'
            }
        });
    })
    
</script>

app/views/documents/_documents_index.html.erb
<div class="left-section">
	<%= render partial: "timeline/left_section" %>
</div>	
<div class="center-section">
	<%= render :partial=>'documents/documents_center_sec',:locals=>{:member_nutrients=> @member_nutrients} %>
</div>	
<div class="right-section">
	<%= render :partial=>'documents/documents_right_sec',:locals=>{:member_nutrients=> @member_nutrients} %>
</div>	

app/views/documents/_documents_right_sec.html.erb
<div class="singleBx-type15">
    <div class="page-title-1">Keep your Documents updated!</div>
    <!-- <ul class="list-type-10 clearFix">
        <li class="line"></li>
        <li>
            <p class="page-title-1a FL">Birth Certificate</p>
            <%#= link_to "",'#html', data: {pop: new_document_path(member_id: @member.id)}, class: "txt-link-type1 icon-upload-file FR", style: "padding-bottom:6px;" %>    
        </li>
        <li>
            <p class="page-title-1a FL">Admission Card</p>
            <%#= link_to "",'#html', data: {pop: new_document_path(member_id: @member.id)}, class: "txt-link-type1 icon-upload-file FR", style: "padding-bottom:6px;" %>
        </li>
        <li>
            <p class="page-title-1a FL">Immunisation Card</p>
            <%#= link_to "",'#html', data: {pop: new_document_path(member_id: @member.id)}, class: "txt-link-type1 icon-upload-file FR", style: "padding-bottom:6px;" %>
        </li>
        <li>
            <p class="page-title-1a FL">Sample Document</p>
            <%#= link_to "",'#html', data: {pop: new_document_path(member_id: @member.id)}, class: "txt-link-type1 icon-upload-file FR", style: "padding-bottom:6px;" %>
        </li>
    </ul> -->
</div>

app/views/documents/create.js.erb
<% if @document.errors.blank? %>
  $.fn.close();
  $(".globel-msg").html("<span>" + "<%= @message %>" + "</span>")
  $("table tbody.member_documents").html("<%= j render partial: 'documents/document_list' %>")
<% else %>
    $('.error').remove();
	$.each($("[class*='js-']"), function( index,input ) {
		$(input).removeClass("border-red");
	})
	<% @document.errors.messages.each do |k,v| %>
		$('.js-' + "<%= k.to_s %>").addClass("border-red");		
		$('.js-' + "<%= k.to_s %>").after("<span class='error'><%= v.first %></span>");
<% end %>
<% end %>

app/views/documents/delete_attachment.js.erb
$("#js-file-<%= @document.id %>").remove();

app/views/documents/destroy.js.erb
$("table tbody.member_documents").html("<%= j render partial: 'documents/document_list' %>")

app/views/documents/documents_info.html.erb
<div class="logoBack">
  <h2 class="space-bottom-1"><i class="icon-document-color info-icon"></i> Documents</h2>
    <ul class="pin-list">
        <li>Upload and securely preserve key documents for your child. </li>
    </ul>
    <div class="form-type3">
        <div class="form-action-row">
            <input type="button" value="Got it!" class="btn btn-type2" style="margin-left:42px;" onclick="$.fn.close();" />
        </div>
    </div>
</div>

app/views/documents/edit.html.erb
<h2>
    Edit Document
</h2>
<%= render partial: 'form' %>

app/views/documents/index.html.erb
<div class="left-section">
	<%= render partial: "timeline/left_section" %>
</div>	

<div class="center-section">
	<%= render partial: 'documents/documents_center_sec' %>
</div>
<div class="right-section">
	<%= render partial: 'documents/documents_right_sec' %>
</div>

<script type="text/javascript">
	update_left_nav("<%= @member.id %>", "documents");
	if("<%= @display_documents_info %>"=="true"){
	    $.fn.popclick({pop: "<%= documents_info_documents_path %>", width: "600" })
	  }
</script>

app/views/documents/list_google_docs.html.erb
<b> Select The document You want to upload </b>
<br/><br/>
<% @google_docs.each do |doc| %>
	<p>
		<%= link_to doc, download_google_doc_path(doc_upload: doc, member_id: @member.id), remote: true %>
	</p>
<% end %>	

app/views/documents/new.html.erb
<h2>
    Upload Document
</h2>
<%= render partial: 'form' %>

app/views/documents/search.js.erb
<%# debugger %>
$("table tbody.member_documents").html("<%= j render partial: 'documents/document_list' %>")

app/views/documents/update.js.erb
<% if @document.errors.blank? %>
  $.fn.close();
  $("table tbody.member_documents").html("<%= j render partial: 'documents/document_list' %>")
<% end %>